[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20", "python3", "python3Packages.yt-dlp"]

[phases.build]
cmds = [
    "npm ci --legacy-peer-deps --prefer-offline --no-audit"
]

[start]
cmd = "npm start"
